export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGES = 'DELETE_FLASH_MESSAGES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const QUESTION_GOT = 'QUESTION_GOT';
